version: '3.3'

services:
  plotlab_server:
    image: plotlabserver:latest
    container_name: plotlabserver
    hostname: plotlabserver
    network_mode: "host"
    ipc: "host"
    #entrypoint: sh -c '(xeyes &) && ./plotlabserver'
    #entrypoint: sh -c 'tail -f /dev/null'
    environment:
     # - DISPLAY_MODE=${DISPLAY_MODE:-native}
      - DISPLAY_MODE=${DISPLAY_MODE:-window_manager}
     # - DISPLAY_MODE=${DISPLAY_MODE:-headless}
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
    ports:
      - 12345:12345
      - 12346:12346
      - 12347:12347
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - .log/plotlabserver:/var/log/plotlab
  ros-master:
    image: ros:noetic-ros-core
    container_name: ros-master
    command: stdbuf -o L roscore
    restart: always
    user: nobody
    environment:
      - "ROS_HOME=/tmp/adore/.log/.ros"
      - "ROS_MASTER_URI=http://127.0.0.1:11311"
      - "ROS_HOSTNAME=127.0.0.1"
    volumes:
        - .ros:/tmp/adore/.ros
  adore-cli:
    image: adore-cli:latest
    container_name: adore-cli
    user: adore-cli
    privileged: true
    hostname: adore-cli
    network_mode: "host"
    command: /bin/bash -c "bash tools/adore-cli_start.sh"
    environment:
      - "ADORE_SOURCE_DIR=/tmp/adore"
      - "BAG_OUTPUT_DIRECTORY=/tmp/adore/.log/.ros/bag_files"
      - "ROS_HOME=/tmp/adore/.log/.ros"
      - "HISTFILE=/tmp/adore/.zsh_history"
      - "ROS_MASTER_URI=http://127.0.0.1:11311"
      - "ROS_HOSTNAME=127.0.0.1"
    depends_on:
      - ros-master
      - plotlab_server
    build:
      context: .
      network: host
      dockerfile: docker/Dockerfile.adore-cli
      args:
        - USER=adore-cli
        - UID=${UID:-1000}
        - GID=${GID:-1001}
    volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - .bash_history:/home/adore-cli/.bash_history
        - ./:/tmp/adore
