name: CI 
on: push

jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 512
          swap-size-mb: 1024
          remove-dotnet: 'true'
          remove-android: 'true'
          remove-haskell: 'true'
          remove-codeql: 'true'
        run: |
          df -h
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
        #  submodules: 'recursive'
      - name: Install requirements
        run: |
          df -h
          sudo apt-get update
          sudo apt-get install -y make
      - name: Build
        run: |
          df -h
          source adore.env && make build
      - name: CI Test
        run: |
          df -h
          source adore.env && make ci_test
      - name: Test
        run: |
          df -h
          source adore.env && make test
      - name: Simulate
        run: |
          export DISPLAY_MODE=headless
          make run_test_scenarios
