name: CI 
on: push

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 35000
          swap-size-mb: 1024
          remove-dotnet: 'true'
          remove-android: 'true'
          remove-haskell: 'true'
          remove-codeql: 'true'
      - name: Checkout
        uses: actions/checkout@v2
        #with:
        #  submodules: 'recursive'
      - name: Install requirements
        run: |
          sudo apt-get update
          sudo apt-get install -y make
      - name: Build
        run: |
          source adore.env && make build
      - name: CI Test
        run: |
          source adore.env && make ci_test
      - name: Test
        run: |
          source adore.env && make test

